
blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Have a Question?
    url: https://stackoverflow.com/questions/tagged/react-chartjs-2
    about: Feel free to ask questions on Stack Overflow
